### ISSUE TITLE
Slider valueChanged only on release

### ISSUE THREAD

**Issue by zanesc** [GAM3RG33K/flutter_settings_screens#12] opened 2020-06-18 23:57 UTC
Hi, is it possible to support only updating the value in the CustomCacheProvider when the slider is released? I have the CustomCacheProvider hooked up to network calls that update data on my server but it updates it for every increment in the slider which is not good for my use case. I know in iOS with swift you can accomplish this by setting mySlider.isContinuous = false.

**Comment by GAM3RG33K** [comment] 2020-06-19 03:26
That's a genuine problem. However I have not modified any flutter widgets yet, so the slider being used is the flutter's version of the slider which seems to be continuous in updates.

I'll try to find out if we can do something about it or not. Will update any progress here for reference.

**Comment by GAM3RG33K** [comment] 2020-06-23 16:27
@zanesc check this [commit](https://github.com/GAM3RG33K/flutter_settings_screens/tree/patch-slider-update) out.
This should fulfill the slider requirements. I have added two additional callbacks which were available in `slider` widget

**Comment by GAM3RG33K** [comment] 2020-06-26 03:26
@zanesc If this fix works for you, I am gonna merge this in the master and then release an update of the plugin soon.

**Comment by zanesc** [comment] 2020-06-26 11:58
@GAM3RG33K yes this implementation works! My reasoning for the way that I did it in my pull request was so that you can use the callbacks for either of the three states yet decide only the ones which you want to update the cache for. However, I have changed my requirements and your implementation would suffice. Thanks again.

**Comment by GAM3RG33K** [comment] 2020-07-24 02:05
Closing this since this issue is resolved and verified. Feel free to file a new issue if the solution for this does not work as intended.

**Closed by GAM3RG33K** 2020-07-24 02:05 UTC
