### ISSUE TITLE
Update SettingsTile programatically

### ISSUE THREAD

**Issue by zanesc** [GAM3RG33K/flutter_settings_screens#18] opened 2020-07-17 20:16 UTC
Hey, I have built an options screen that has a "Reset to Defaults" option on it but I can't get the SettingsTiles to update after resetting the settings to the defaults by using Settings.setValue(). I have the SettingsContainer inside a ChangeNotifier/Consumer which listens to changes to my cacheProvider. Setting the values triggers an update to the Consumer however the SettingsTiles do not change to the new values.

Is there another way to set the values programatically to update the UI?

**Comment by GAM3RG33K** [comment] 2020-07-24 02:00
Sorry for the very late response.
Can you post the code for the same? It'll help me understand the issue that you are facing.

Make sure that you call `setState` when resetting settings with your logic as A settings tile value should update only on the rebuild of the widget, in most cases it is handled for only setting at a time.

**Comment by GAM3RG33K** [comment] 2020-09-07 09:52
@zanesc can you provide any update? 
Also, If this issue is no longer reproducible, please inform me so that I can close this.

**Comment by GAM3RG33K** [comment] 2020-12-13 05:48
closing due to no response.

**Closed by GAM3RG33K** 2020-12-13 05:48 UTC

**Comment by ansshkki** [comment] 2021-03-01 16:12
@GAM3RG33K  I have the same issue, this is the code I have:

```dart
              SettingsGroup(title: "Notifications", children: [
                SwitchSettingsTile(
                  title: "Enable notifications",
                  settingKey: "notifications_switch",
                  onChange: (value) async {
                    await Settings.setValue("notifications_start", value);
                    await Settings.setValue("notifications_end", value);
                    setState(() {});
                  },
                  childrenIfEnabled: [
                    CheckboxSettingsTile(
                      defaultValue: true,
                      title: "Periods start notifications",
                      settingKey: "notifications_start",
                      onChange: (value) async {
                        if (value) {
                          enable(forStart: true);
                        } else {
                          disable(forStart: true);
                          if (!Settings.getValue("notifications_end", false)) {
                            await Settings.setValue("notifications_switch", false);
                            setState(() {});
                          }
                        }
                      },
                    ),
                    CheckboxSettingsTile(
                      title: "Periods end notifications",
                      settingKey: "notifications_end",
                      onChange: (value) async {
                        if (value) {
                          enable(forStart: false);
                        } else {
                          disable(forStart: false);
                          if (!Settings.getValue("notifications_start", false)) {
                            await Settings.setValue("notifications_switch", false);
                            setState(() {});
                          }
                        }
                      },
                    ),
                  ],
                ),
              ])
```

I want the switch tile to be false when both `notifications_start` and `notifications_end` are false, but the UI doesn't change when `setState()` is called.

**Comment by msthoma** [comment] 2021-03-22 12:15
@ansshkki if you still have the issue, try wrapping the `SettingsGroup` or `SettingsScreen` with a Scaffold or Container with a unique key, like this:

```dart
Container(
      key: UniqueKey(),
      child: SettingsScreen(...),
)
 ```
It solved the issue for me, now when `setState()` is called the tiles are updated.

**Comment by ansshkki** [comment] 2021-03-22 12:28
@msthoma Thank you, that's working!
