### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by JupiterThreads** [GAM3RG33K/flutter_settings_screens#55] opened 2021-08-14 15:28 UTC
If you omit the subtitle for SimpleSettingsTitle it will set a null value for subtitle, which will override the default value of empty string in the _SettingsTile class causing the null check operator error, which can be found on line 156 in base_widgets.dart.

At the moment a work around is to provide an empty string to subtitle for SimpleSettingsTile.

**Comment by GAM3RG33K** [comment] 2021-10-09 03:57
I believe this is fixed in the lastest release v0.3.2-null-safety, so closing this issue, 
Please verify the same from your end & re-open with a sample code & logs if the issue is not fixed.

**Closed by GAM3RG33K** 2021-10-09 03:57 UTC
