### ISSUE TITLE
Unhandled Exception: HiveError: This is an internal error

### ISSUE THREAD

**Issue by LiveRock** [GAM3RG33K/flutter_settings_screens#53] opened 2021-07-28 09:36 UTC
When I do 
```
await Settings.init(
      cacheProvider: tHiveCache() ,
    );

```
I get the error and could not proceed:

> Unhandled Exception: HiveError: This is an internal error

I am cracking my head over this for many days without a solution...
help!

**Comment by GAM3RG33K** [comment] 2021-07-30 15:06
Hive Exception is totally a different issue all together, however I have been through this issue & there's no proper explanation from the dev of `Hive` as well about it.

I can suggest some tips to prevent it, it may resolve your issue but I am not sure about it either.

Here it goes:
1. Make sure that you don't have corrupted data in any of your hive boxes
2. Ensure that everything you put in the box is supporte, i.e type is supported by default or has a Hive adapter for custom objects
3. Check is the `box` is open already or not, if the box is open, then do not open it again, just retrieve the box directly
4. Clear storage & uninstall the app once before testing these changes, just be sure that the existing data is not causing the issue.

 That's all I can think of at the moment, I suggest you checkout the original repository issues, you may find something userful there.

**Comment by GAM3RG33K** [comment] 2021-07-30 15:08
I am looking into this for now in the plugin's code, just to be sure.

**Comment by GAM3RG33K** [comment] 2021-08-01 15:51
I have updated the example code from my side to check if the box is open or close. Please check the example code in latest commit or checkout the latest update [`v0.3.1-null-safety`](https://pub.dev/packages/flutter_settings_screens/versions/0.3.1-null-safety)


Closing this for now, If you think the issue is caused by something from the library's code then feel free to re-open it.

**Closed by GAM3RG33K** 2021-08-01 15:51 UTC
